Tweak `Display` impl of `BinomialExtensionField`
Plonky3/Plonky3 pull request #153
Opened 2023-10-11 00:46 UTC by dlubarov

Clippy didn't like the way it was building up a string.

2023-10-11 01:51 UTC, LKY-stephen approved these changes
LGTM, do we need to update CI?

2023-10-11 01:53 UTC, LKY-stephen commented
BTW; This change will show `x^1`.

2023-10-11 01:58 UTC, Nashtare commented
Wouldn't we additionally want to skip 0 coeffs? (Even simplify also the case of coeffs being 1)

2023-10-11 02:08 UTC, LKY-stephen commented
I quickly write a test for cubicbef, the result seems wrong
`"1656410110 + 1528177553i + 15242231 + 2111298671i*X^2 + 436540726 + 1010126309i*X^3"`

2023-10-11 02:11 UTC, LKY-stephen requested changes
su

2023-10-11 02:11 UTC, LKY-stephen commented on field/src/extension/binomial_extension.rs
> +            write!(f, " + {}*X^{}", x, i + 1)?;
should be `i` here; or skip first

2023-10-11 02:52 UTC, dlubarov commented on field/src/extension/binomial_extension.rs
> +            write!(f, " + {}*X^{}", x, i + 1)?;
Oh right, fixed

2023-10-11 02:53 UTC, dlubarov commented
I made the two changes, removing `^1` as the prior code did, and removing zero terms. Also removed multiplication by `1`. Thanks!

2023-10-11 04:52 UTC, LKY-stephen requested changes

2023-10-11 04:52 UTC, LKY-stephen commented on field/src/extension/binomial_extension.rs
> +            .filter(|(_, x)| !x.is_zero())
It seems `EF::ZERO` will print nothing,

2023-10-11 16:06 UTC, dlubarov commented on field/src/extension/binomial_extension.rs
> +            .filter(|(_, x)| !x.is_zero())
Good point, fixed and added more tests

2023-10-12 02:10 UTC, LKY-stephen approved these changes

2023-10-12 03:45 UTC, merged