Cleaning up tests and round constants
Plonky3/Plonky3 pull request #299
Opened 2024-04-02 16:36 UTC by SyxtonPrime

Removed the import of HorizenLabs Poseidon2 implementation from BabyBear and Goldilocks tests. Instead saved the relevent constants in a file in Poseidon2 and computed a couple of test evaluations using sage to check results again.

I haven't modified the bn254 tests as that version of Poseidon2 is a little different (Width is not a multiple of 4) so I don't currently have a sage implementation of it. Not sure how much we are planning to support bn254 anyway so just going to leave that as is for now.

Additionally, minor changes to the Poseidon2 algorithm where I have split apart the constants into external and internal round constants. The external constants are each the form [F; WIDTH] where as the internal ones are directly elements of F so it doesn't really make sense to save the constants together.

2024-04-02 17:49 UTC, jorgeantonio21 reviewed
LGTM

2024-04-02 17:49 UTC, jorgeantonio21 commented on poseidon2/src/round_constants.rs
> +// We save the constants used by the Poseidon2 implementation by Horizon Labs:
nit: Horizen*

2024-04-02 18:51 UTC, SyxtonPrime commented on poseidon2/src/round_constants.rs
> +// We save the constants used by the Poseidon2 implementation by Horizon Labs:
Good catch, just fixed that.

2024-04-03 08:43 UTC, unzvfu requested changes
Looks good overall, just a few minor things that can be improved.

2024-04-03 08:43 UTC, unzvfu commented on bn254-fr/src/poseidon2.rs
> +
Shorter, clearer, and more idiomatic:
```suggestion
        let internal_start = ROUNDS_F / 2;
        let internal_end = (ROUNDS_F / 2) + ROUNDS_P;
        // need to make `round_constants` mutable above for this to work
        let internal_round_constants = round_constants
            .drain(internal_start..internal_end)
            .map(|vec| vec[0])
            .collect::<Vec<_>>();
        // optional rename; probably simpler to just to call the original variable `external_round_constants`
        let external_round_constants = round_constants;
```

2024-04-03 14:00 UTC, SyxtonPrime commented on poseidon2/src/round_constants.rs
> +// [[5, 7, 1, 3], [4, 6, 1, 1], [1, 3, 5, 7], [1, 1, 4, 6]]
In Poseidon2, the external (full) round matrix is built from a 4x4 MDS matrix. Happy to reword this comment though.

2024-04-03 14:02 UTC, SyxtonPrime commented on poseidon2/src/lib.rs
>              internal_linear_layer: internal_mds,
I completely agree. I might make this change in a future PR though as I'll introduce external_linear_layer as an argument and it's natural to fix this at the same time.

2024-04-03 14:03 UTC, SyxtonPrime commented on poseidon2/src/lib.rs
> +            internal_constants.push(rng.gen::<F>());
Sounds good

2024-04-03 15:42 UTC, unzvfu approved these changes
Looks good! Just a few leftover comments to remove.

2024-04-03 15:42 UTC, unzvfu commented on bn254-fr/src/poseidon2.rs
> +        // need to make `round_constants` mutable above for this to work
Don't need this comment anymore.

2024-04-03 15:42 UTC, unzvfu commented on bn254-fr/src/poseidon2.rs
> +        // optional rename; probably simpler to just to call the original variable `external_round_constants`
Don't need this comment anymore.

2024-04-03 15:50 UTC, merged