Mersenne31 fermat inverse
Plonky3/Plonky3 pull request #53
Opened 2023-08-08 22:54 UTC by JL2718

This is just straight theft from #40, but.. 

Bench results
```
shift_inverse           time:   [357.93 ns 368.95 ns 383.44 ns]
fermat_inverse          time:   [84.336 ns 84.488 ns 84.673 ns]
```

2023-08-09 13:37 UTC, unzvfu requested changes
That's great! Thanks!

Could you please remove the inverse implementations from the benchmark and just the new version from the `Mersenne31` crate in the benchmarks?

Also, I think for the tests you can remove `shift_inverse` and just check that (for `x != 0` and `x != 1`) the calculated inverse `z` is different from `x` and that `x * z == 1`.

2023-08-09 21:58 UTC, JL2718 commented
Note that when I change the bench to compute the inverse on the object, there is a ~20ns slowdown, possibly just from dereferencing &self. Something to be aware of when doing comparisons.

2023-08-18 13:57 UTC, unzvfu reviewed
Sorry for the delay. This looks good to me. I'll fix up the conflicts with `main` and use your `inverse_random()` in the `field_testing` crate.

2023-08-18 14:03 UTC, unzvfu approved these changes

2023-08-18 14:04 UTC, merged